management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port : 8080
rabbitmq:
  internal-mail:
    exchanges: internal.exchange
    listener:
      queue-name: email-queue
    routing-key: internal.mail.routing-key

spring:
  application:
    name: ms-email-service
  rabbitmq:
    addresses: amqps://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@armadillo.rmq.cloudamqp.com/${RABBITMQ_USERNAME}
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'

eureka:
  instance:
    hostname: ${MS_EMAIL_HOST}  # Public domain name
    nonSecurePort: 80  # Standard HTTP port
    securePortEnabled: false  # Enable if you're using HTTPS
    preferIpAddress: false  # Use the hostname instead of the IP address
    statusPageUrlPath: /actuator/info  # Default status page path
    healthCheckUrlPath: /actuator/health  # Default health check path
  client:
    serviceUrl:
      defaultZone: "${MS_EUREKA_URL}/eureka"
    fetch-registry: true
    register-with-eureka: true